[project]
name = "3g5"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "jinja2>=3.1.6",
    "matplotlib==3.10.7",
    "pandas>=2.3.3",
    "pandas-stubs==2.3.2.250926",
    "scipy>=1.16.2",
    "scipy-stubs==1.16.2.4",
]
